# Generated by Django 4.0.4 on 2022-06-24 22:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_del_comentario', models.CharField(max_length=40)),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('autor_del_comentario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('libro_comentado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.cataloguebook')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
