# Generated by Django 4.0.4 on 2022-06-25 21:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_comentario_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
