# Generated by Django 4.0.4 on 2022-06-25 21:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_alter_booktorate_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktorate',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
