# Generated by Django 3.2.8 on 2022-06-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cataloguebook_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloguebook',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images_book', verbose_name='image'),
        ),
    ]
