# Generated by Django 3.2.8 on 2022-06-19 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_creation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
