# Generated by Django 3.2.8 on 2022-06-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='avatar'),
        ),
    ]
